## 1
name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  pull_request:
    branches:
      - master

## 2
jobs:
  code_style_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Kotlin Code Formatter
        run:  |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.40.0/ktlint && chmod a+x ktlint
          ./ktlint -F
          echo "Committing Formatted Files"
          git config --global user.email "ahmedyehya1992@gmail.com"
          git config --global user.name "ahmedyehya92"
          git add .
          git commit -m "Fixing Formats"
          git push origin HEAD:<master>

  update_branch_tags:
    needs: [ code_style_format ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version
        id: bump_version
        uses: oflynned/Android-Semantic-Release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  ## 3
  unit_tests:
    needs: [ update_branch_tags ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test
  build:
    needs: [ unit_tests ]
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      # 2
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 3
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      # 4
      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      # 5
      - uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt