## 1
name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  push:

## 2
jobs:
  code_style_format:
    runs-on: ubuntu-latest
    steps:
      - name: Get Kotlin Code Formatter
        run:  |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.40.0/ktlint && chmod a+x ktlint
          ./ktlint -F


  add_format_edit:
    needs: [ code_style_format ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Apply Formatted Files
        run: |
          echo "Committing Formatted Files"
          git config --global user.email "ahmedyehya1992@gmail.com"
          git config --global user.name "ahmedyehya92"
          git add .
          git commit -m "Fixing Formats"
          git push
